### ISSUE TITLE
Does not work with Create react app import { ReactComponent } 

### ISSUE THREAD

**Issue by evanjmg** [Em-Ant/jest-transformer-svg#4]
If we import svgs directly with import { ReactComponent } from '*.svg' this does not work, it errors

**Comment by Em-Ant** [comment]
can you provide the whole code example, or a link to where i can have a look ?

I've not tried to use it with CRA, i guess it's a configuration issue.

See [this issue](https://github.com/facebook/create-react-app/issues/12430). I think it may explain your problem.
